### PR TITLE
Added user ldap bulk import feature

### PR DESCRIPTION
**Pull request by michaelscheurer**
New feature to allow users making bulk import. Added with new settings.

Bulk import can be executed under users -> menu (LDAP Bulk Import)

### CODE REVIEW

**Comment by koma85** [comment]
I'd love to try this!

**Comment by fernwerker** [comment]
I'd love to see this feature. Is there a way of helping out?

**Comment by heiglandreas** [comment]
I'm absolutely and terribly sorry for not giving any feedback on this PullRequest for over two years. That usually is not my way of doing this. 

And thank you very much for taking the time and building this cool feature.

Nevertheless I have to say that a bulk-import is **not** in the scope of this plugin. The plugins scope is to *authenticate* a given user. Bulk-Importing is something entirely different. And you might have seen that as you didn't need to modify my current code. The changes you did, were adding new code. That usually is a good hint, that you are adding functionality, that can also be added in it's own plugin. 

So I'd strongly encourage you to create a separate plugin – perhaps based on or requiring authLdap – with it's own lifecycle.

It has also the advantage that you are not tied to authLdap but you can use *any* LDAP- (or AD-) plugin out there.

Feel free to reach out if you think I can help you in achieving that, and I'll try to give you feedback in a more timely manner.

**Comment by fernwerker** [comment]
Sorry from my side, I got a misunderstanding in "bulk import".
I thought it was a feature to trigger the registration of a user from LDAP to Wordpress.

Background:
* I run a multisite instance
* current group-role-mapping mechanisms are based for a single wordpress instance 
  * no super-admin support
  * no separation of groups for different websites within one network
  * all roles are mapped to the root-website of the network

Idea:
* keep it small and simple and have a "single user import from ldap" to register a user
* for me as a super-admin I can input the username of a user that exists in LDAP and needs access to a certain wordpress website within my network
* the function pulls all information without risk of mistyping or anything and registers this user
* I can adjust all its rights (e.g. be an admin for a certain website)

Benefit:
* the user does not need to login first to get registered within wordpress and then wait for an admin to give him the correct rights

@heiglandreas: Is there any plan on this or a possibility to have it merged, if I had this? Most of the functions needed are already there. It's only a new input form and the logic to trigger a registration.

**Comment by heiglandreas** [comment]
Well... You could actually do that already when the user belongs to different groups within the LDAP. You can match the WordPress-Roles to groups within the LDAP. So when the user is member of a certain group in LDAP they will get a certain role assigend in WordPress as soon as they log in. So even less administrative work for the admin as they do not need to log into the WP-installation to import a user and then edit their roles. Add the appropriate group to the user in LDAP and let the user log in whenever they are ready for it.

Feel free to ping me at authldap AT heigl DOT org if you need more info on that

**Pull request closed without merging**
